### ISSUE TITLE
Redis connection fails silently

### ISSUE THREAD

**Issue by slorek** [ministryofjustice/hmpps-book-secure-move-frontend#96]
If the Redis connection is not established, express-session does not throw an error, instead we get errors such as:

```
error: Cannot read property 'authExpiry' of undefined {"stack":"TypeError: Cannot read property 'authExpiry' of undefined\n    at isAuthExpired (/home/node/app/common/middleware/authentication.js:45:20)\n    at ensureAuthenticated (/home/node/app/common/middleware/authentication.js:4:8)\n    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/node/app/node_modules/express/lib/router/index.js:317:13)\n    at /home/node/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/node/app/node_modules/express/lib/router/index.js:275:10)\n    at Function.handle (/home/node/app/node_modules/express/lib/router/index.js:174:3)\n    at router (/home/node/app/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)"}
GET / 500 99.956 ms - 1481
Template render error: (/home/node/app/common/templates/error.njk)
  Template render error: (/home/node/app/common/templates/includes/messages.njk)
  Error: req.flash() requires sessions
    at Object._prettifyError (/home/node/app/node_modules/nunjucks/src/lib.js:36:11)
    at /home/node/app/node_modules/nunjucks/src/environment.js:567:19
    at eval (eval at _compile (/home/node/app/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:88:12)
    at eval (eval at _compile (/home/node/app/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:212:12)
    at eval (eval at _compile (/home/node/app/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:294:12)
    at /home/node/app/node_modules/nunjucks/src/environment.js:575:11
    at Template.root [as rootRenderFunc] (eval at _compile (/home/node/app/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:111:3)
    at Template.render (/home/node/app/node_modules/nunjucks/src/environment.js:556:10)
    at eval (eval at _compile (/home/node/app/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:293:10)
    at fn (/home/node/app/node_modules/a-sync-waterfall/index.js:26:24)
```

**Comment by teneightfive** [comment]
This was fixed by #119
